# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/terraform-csr', '.']
- name: 'gcr.io/${PROJECT_ID}/terraform-csr'
  args: ['version']
images: ['gcr.io/${PROJECT_ID}/terraform-csr']
